// <auto-generated />
namespace Week3ClubDomain2122.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Clubmodeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clubmodeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "202111021324530_Club model added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
